// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACvpTPatP00Bfo9ID-_2ZIhkmrcE5YQnQ',
    appId: '1:544226163982:web:cd130be05aef567e7deb5f',
    messagingSenderId: '544226163982',
    projectId: 'recipeapp-e86eb',
    authDomain: 'recipeapp-e86eb.firebaseapp.com',
    storageBucket: 'recipeapp-e86eb.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzq75SXpOTekpCExjLu91mH-la5AngIEY',
    appId: '1:544226163982:android:bf26cccd09e26d0d7deb5f',
    messagingSenderId: '544226163982',
    projectId: 'recipeapp-e86eb',
    storageBucket: 'recipeapp-e86eb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN2LrnQpo1CgW0qG6_fLQmS_EXvwfptsQ',
    appId: '1:544226163982:ios:7459e5e380608ef97deb5f',
    messagingSenderId: '544226163982',
    projectId: 'recipeapp-e86eb',
    storageBucket: 'recipeapp-e86eb.firebasestorage.app',
    iosBundleId: 'com.example.lab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACvpTPatP00Bfo9ID-_2ZIhkmrcE5YQnQ',
    appId: '1:544226163982:web:07169b85c90121777deb5f',
    messagingSenderId: '544226163982',
    projectId: 'recipeapp-e86eb',
    authDomain: 'recipeapp-e86eb.firebaseapp.com',
    storageBucket: 'recipeapp-e86eb.firebasestorage.app',
  );
}
